# CircleCI 2.0 configuration file
#
#
#
version: 2
jobs:
  build:
    machine: true # Use a Linux VM
    working_directory: ~/repo # Default working directory, where project will be cloned

    steps:
    - checkout

    - run:
        name: "Setup custom environment variables"
        command: |
          echo 'export NODE_ENV="test"' >> $BASH_ENV

    - run: docker-compose up
    - run: npm install
    - run: npm test

#    - save_cache:
#        key: v1-myapp-{{ arch }}-{{ checksum "project.clj" }}
#        paths:
#        - node_modules
